[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs ; data 폴더 업로드를 위해 필수
lib_ldf_mode = deep
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.12
    ricmoo/QRCode @ ^0.0.1  ;